name = "Less than Compact"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e7abc3a4d5f0df3eeb13d14c7fce455839807c43f031eb2be0fddbfb651be9d"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
