name = "Less than Compact"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9230a9c248edeb88bab2f9e0d58e80c3991bd8e54a90889c571848d02cbafbc8"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
