name = "Less than Compact"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07c97e9b6165f55b9c30c25bb7694da1bcbee47bf2e5ce4d69d21a33f87c8a07"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
